on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    strategy:
      matrix:
        flavor: [Development, Staging, Production]  # Define the flavors here
        main_file: [main_devlopment.dart, main_staging.dart, main_production.dart]  # Define the entry point files

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '23'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Build APK for each flavor with a specific entry point
      - run: flutter build apk --flavor ${{ matrix.flavor }} --release -t lib/${{ matrix.main_file }}
        name: Build APK for ${{ matrix.flavor }}

      # Build iOS app for each flavor with a specific entry point
      - run: |
          flutter build ios --flavor ${{ matrix.flavor }} --release --no-codesign -t lib/${{ matrix.main_file }}
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app-${{ matrix.flavor }}.ipa Payload
        name: Build iOS App for ${{ matrix.flavor }}

      # Upload the artifacts (APK/IPA) for each flavor
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/apk/release/app-${{ matrix.flavor }}-release.apk,build/ios/iphoneos/app-${{ matrix.flavor }}.ipa
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}