on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    strategy:
      matrix:
        flavor: [Development, Staging, Production]  # Define the flavors here

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '23'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Android Build for each flavor
      - run: flutter build apk --flavor ${{ matrix.flavor }} --release -t lib/main_staging.dart --split-per-abi
        name: Build APK for ${{ matrix.flavor }}

      # iOS Build for each flavor
      - run: |
          flutter build ios --flavor ${{ matrix.flavor }} --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app-${{ matrix.flavor }}.ipa Payload
        name: Build iOS App for ${{ matrix.flavor }}

      # Upload artifacts for each flavor
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/apk/${{ matrix.flavor }}/*,build/ios/iphoneos/app-${{ matrix.flavor }}.ipa
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}